name       : libgltf
version    : 0.1.0
release    : 2
source     :
    - https://dev-www.libreoffice.org/src/libgltf/libgltf-0.1.0.tar.gz : 119e730fbf002dd0eaafa4930167267d7d910aa17f29979ca9ca8b66625fd2da
license    : MPL-2.0
component  : programming.library
summary    : Library for rendering glTF models
description: |
    libgltf is a library for rendering glTF models -- development glTF, the GL
    Transmission Format, is the runtime asset format for the GL APIs: WebGL,
    OpenGL ES, and OpenGL. glTF bridges the gap between formats used by modeling
    tools and the GL APIs.
builddeps  :
    - pkgconfig(cppunit)
    - pkgconfig(epoxy)
    - pkgconfig(gl)
    - pkgconfig(glm)
    - pkgconfig(libpng)
    - pkgconfig(x11)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
